version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - lantern-network 
    ports:
      - 80:8080
    environment:
      MQTT_URL: "mqtt://lantern:ilovelamp@mqtt:1883"
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    command: ["./bin/wait-for-postgres.sh", "postgres", "./bin/server.sh"]

  mqtt:
    hostname: mqtt
    image: jameslinnegartw/lantern
    depends_on:
        - postgres
    restart: always
    volumes:
      - ./mqtt/conf:/etc/mosquitto
    ports:
      - 1883:1883
    networks:
      - lantern-network 
  postgres:
    image: postgres:10.4
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      ALLOW_IP_RANGE: '0.0.0.0/0'
    networks:
      - lantern-network 
networks:
  lantern-network:
    driver: bridge # a user defined bridge is required; the default bridge network doesn't support name resolution